# This Github workflow will run jobs to build java-app.
name: java-app
on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: write
jobs:
  setup-stage-gate:
    uses: ploigos/ploigos-github-workflows/.github/workflows/setup-stage-gate.yaml@main
  setup-app-clone:
    uses: ploigos/ploigos-github-workflows/.github/workflows/setup-app-clone.yaml@main
  ci-stage-gate:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-stage-gate.yaml@main
  ci-generate-metadata:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-generate-metadata.yaml@inputs
    with:
      verbose: 'true'
      image: 'ubi8-minimal'
      imagePullPolicy: 'Always'
      venvPath: '.'
      stepRunnerPackageName: 'psr'
      stepName: 'test-step'
      stepRunnerConfigDir: '/opt/'
  ci-package-application:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-package-application.yaml@main
  ci-create-container-image:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-create-container-image.yaml@main
  ci-push-container-image-to-repository:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-push-container-image-to-repository.yaml@main
  dev-stage-gate:
    uses: ploigos/ploigos-github-workflows/.github/workflows/dev-stage-gate.yaml@main
  dev-deploy-or-update-environment:
    uses: ploigos/ploigos-github-workflows/.github/workflows/dev-deploy-or-update-environment.yaml@main
  test-stage-gate:
    uses: ploigos/ploigos-github-workflows/.github/workflows/test-stage-gate.yaml@main
  test-deploy-or-update-environment:
    uses: ploigos/ploigos-github-workflows/.github/workflows/test-deploy-or-update-environment.yaml@main
  report:
    uses: ploigos/ploigos-github-workflows/.github/workflows/report.yaml@main

