# This Github workflow will run jobs to build java-app.
name: java-app
on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: write
jobs:
  setup-stage-gate:
    uses: ploigos/ploigos-github-workflows/.github/workflows/setup-stage-gate.yaml@main
  setup-app-clone:
    uses: ploigos/ploigos-github-workflows/.github/workflows/setup-app-clone.yaml@main
  ci-stage-gate:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-stage-gate.yaml@main
  ci-generate-metadata:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-generate-metadata.yaml@main
  ci-package-application:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-package-application.yaml@main
  ci-create-container-image:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-create-container-image.yaml@main
  ci-push-container-image-to-repository:
    uses: ploigos/ploigos-github-workflows/.github/workflows/ci-push-container-image-to-repository.yaml@main

