# This Github workflow will run jobs to build java-app.
name: java-app
on:
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
permissions:
  pull-requests: write
jobs:
  setup:
    uses:
    - ploigos/ploigos-github-workflows/.github/workflows/setup-stage-gate.yaml@main
    - ploigos/ploigos-github-workflows/.github/workflows/setup-app-clone.yaml@main
  generate-metadata:
    uses:  ploigos/ploigos-github-workflows/.github/workflows/generate-metadata.yaml@main

